# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7459480a106d86187d503abe8d13c3924e0a6eb64bc7df9956116de3d3a84a6087d11b2a2b432575928bff6e21ded2ca64b7bc2e616bc476abfaa2cad6822db9

test:
  secret_key_base: 59e3a059bdec0ccdde86837b62cca644918aeca6a887df6f7693a04893fc6328e85c57c673d82be1a46ee7905e08328348e152f9905174e3375ff40e8e9ea12f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
